language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    - secure: kWn8Bh6TGgb/tcEVKf/58v9JcUpaBO2IQepu+yogV2tu0iF9gN8NZ+oLZ5DnOBU3j62irAC71iT3YB97UjkOVzLcuS1WWZ40ENtYN0xV0klXAJ+l3XQezEs5mpnZ5F40OPAAeghXcjSDJQD6d1NkKIDzK9IprP3wW211aKYaTJU+RA5vdHRx+faNzICY1r4vrhgH3ewXEsHpcOU9H+9NChcnwDsCPEOHUfpQYaT9DJLnl4ec3UYVHSD/cCJK9g5Wc4uL+6AStoN3RyK+HDxGt3mwty+KaverwaD11fRc3BrI/W3JWX/KqCo7ZO2M3b8+sjEjSgS3QD15Dt9AyqtwV/l9m1wKE4ynAc8HK0ATFCHTP7picDRtkufyr3mmcxl6O+GIdkyfeHfhFn13qMnbM/texALf/0NykBEj0AoEDg8E65ISOTyX0alyZ27XmfCOQ7s0AGh0crfkCMYeHeX8NjigvL0aY5zSPBUJFvRNqrp/Xw5l3LBE5l4JF+zOVfBwefUFey/GiqGKWrO4suVphM0wLWmPIYCP+qf1SenjBXlerqDzYvw0S62jHgXmoPFbSlSgE5L+sR/9sE/NxL59IG0uKrw5NR5KVM/jIcfJJqfj+CowZAS59qbQCchyn2opFf+tZhs4625OF9d7fVL0DKCdRT/IjflaTV81uOhdzMc=
env:
  global:
    - secure: KBbiMyCVQ7My6kBqdHMX7yOxOu58RlV2Kn2YDYrQAs5pcbrToLryoZitkQyOL6pvjliFzlhHgFMF4/8yaoO2D3YTH0J2kdWOB7uoLBiI6Sx3tIyP2+J3Tvjm2+9DvFQ1NrRWf4wwciSRIwfiwaGBjZZewSGA1cN48l+cr89lSEdGm7C3zIy5/ZYhtPxMWzEck+zKrAX05lmO4vp6JNOSgSwwQJgmfFQSm6dgzW8U7sCVj679KH5ng9862IYFXhKHsmbQloGD2rGE2UnR2K4osEDhu7bgvhG7dIk+tvIYcRJPYiuXFU27Bi+igiyLk2q+WlXKhfw4j+ttpRwaVruMfQ7YW1dcxh2ruKJTftesGCDbDmYvHPpMDqzMEhDZM9f+rCtThTGfwVDAlKBVq47LmhCIHuIjByf8uMwtJ8LVccpGvM4ymmS3eSao69wwr5lMpjBr/0OPT8Q7SpaDbQCP9ScUZcpY6D6W4o33yr8XCeVZ/hOlVze5NEOR1QPh0UFm1qIroa0v2VGJ1cHsSSHlwaDXfHi4F59ps1/8t7SPxKvvHVCpesrNzIiicEi2isBPLYWBP2nduODoress2PKpWE9mCsz+arjKi5MNwYIOqrr3G2bMr1WsIkyfxLWr/sJWfQOLRldeQrkch2hh8mVSx+XlqDU+kQUTFku+Gz59wAI=
    - secure: tH2iannB7LoAEYXKv92jgTKHDgnrdLGtFCVshUCOtPeLXQS6pqV8FBc0rmpjksJnJc+maZAzxLMHIZSnbHgvJLrmPb5ttKzePR+syaP32tgUHG2MmmgJNmd3+GP3E+6lvV03u6r5tkwzLRprQf9IyBxL0U/ML9DUzwVzXvZaj4EZHOrAjBPBFpWvNGXxdKQt2R6HB/+5wNIrRkySoDtEPEBNh9OCF+AMxHM2hDtikhBCi35GUoH2ZBAsKDe5VZMWq4ldiSgrbV3xwgRx12EuIVpsR8r3/nLl85x2aczh7HrUOvnRNfUb9UZQIhhfV+pVx8qc0VOXz0a+0DhonzOkgT8xeByPym7qaNvK+MpQd5jhD9RQStXEXxrBBVEfjeHfOSipzcYYt66HkfBYZZwhECOaDbrA8rET0B5ylg/rcvaWJ/i0TTJ7++BHZeJl2KAq0C1bvDv3Eig7thxwICRZSJ9nFLQsSOkQtMjWHW6/bvRBnD/6WMEBhuBUz3b75+LsmVmTWc2MFP0deKM8p98F2jKZ+Vz5RIJWhlpQaFHZ0TDXsT3NyDg/9yHJwIVipj6X38xaF0mGgyToGhqsse31Ep3487rBgn+Rby7X95G7MTCaLlw2+fUqT4ns4y+2QPBMIOHKGW/B7Ud8Q8LuaRXhentCWmq4ZycWDymftBFcovU=
